### ISSUE TITLE
[Question] Send attachments

### ISSUE THREAD

**Issue by Pablo-Aldana** [red-made/strapi-provider-email-brevo#1]
Hi!

I'm new to the plugin. I was wondering how can we send attachment on the email?

On our platform our customers buy tickets for events and we need them to send an email with the PDF of the ticket generated on the fly so most likely local files or base64.

KR

**Comment by red-made** [comment]
Hi, every part of the object you pass as an argument is sent to Brevo, so check their API (I can't tell you right now, I tend not to send attachments but download links) to understand how to send attachments.
Otherwise, if you keep the file, perhaps until the end date of the event, you can put the download URL in your email.
